site_name: HayBox Firmware
site_url: https://jonnyhaystack.github.io/haybox
repo_name: HayBox
repo_url: https://github.com/JonnyHaystack/HayBox
copyright: Copyright &copy; 2024 Jonathan Haylett
nav:
  - Overview: index.md
  - Getting started: installation.md
  - Configuration:
    - "Protocol Documentation": proto.md
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.top
    - navigation.tabs
    - navigation.path
    - toc.follow
markdown_extensions:
  - toc:
      permalink: "#"
plugins:
  - privacy
  - social