site_name: HayBox
site_url: https://jonnyhaystack.github.io/haybox
repo_url: https://github.com/JonnyHaystack/HayBox
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress