site_name: HayBox Firmware
site_url: https://jonnyhaystack.github.io/haybox
repo_name: HayBox
repo_url: https://github.com/JonnyHaystack/HayBox
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - toc.integrate
    - toc.follow
markdown_extensions:
  - toc:
      permalink: "#"
plugins:
  - privacy