name: Build and deploy to GitHub Pages

on: [push]

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install build dependencies
        run: |
          sudo apt install pipx
          pipx install poetry

      - name: Check out this repo
        uses: actions/checkout@v4

      - name: Check out HayBox-proto
        uses: actions/checkout@v4
        with:
          repository: JonnyHaystack/HayBox-proto
          path: proto

      - name: Generate protobuf documentation
        run: |
          cp protoc-gen-doc/markdown.tmpl proto/
          docker run --rm \
            -v $(pwd)/docs:/out \
            -v $(pwd)/proto:/protos \
            pseudomuto/protoc-gen-doc --doc_opt=markdown.tmpl,proto.md

      - name: Build site
        run: |
          poetry install
          poetry run mkdocs build

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/
      
  # Deploy job
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    needs: build

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4